import { ArrowDown, ArrowDownToLine, ArrowUpRight, MapPin, MessageCircle, Star } from "lucide-react";
import { Header } from "@/components/header";
import { Logo, MenuPhoto } from "@/components/brand";
import { MenuCard } from "@/components/menu-card";
import { business, whatsappUrl } from "@/lib/business";
import { categories, sauces } from "@/lib/menu";
import { restaurantSchema } from "@/lib/seo";

export default function Home() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(restaurantSchema()).replace(/</g, "\\u003c") }} /><Header /><main id="main">
    <section className="hero" id="home"><div className="container hero-grid">
      <div className="hero-copy"><p className="eyebrow hero-eyebrow"><span /> YOUR HAFIZABAD FOOD FIX</p><h1>BIG FLAVOR.<br /><span>REAL BROS.</span></h1><p className="hero-description">Burgers that hit the spot. Shawarmas worth the craving.<br className="desktop-break" /> Your next favorite bite is right here at 4bros.</p><div className="hero-actions"><a href="#menu" className="button button-red">Explore the menu <ArrowDown size={18} /></a><a href={whatsappUrl} target="_blank" rel="noreferrer" className="hero-text-link"><MessageCircle size={19} /> Order on WhatsApp <ArrowUpRight size={16} /></a></div><div className="hero-footnote"><span className="mini-star">✦</span> Fast food. Full-on flavor. All prices in PKR.</div></div>
      <div className="hero-visual"><span className="hero-outline-word" aria-hidden="true">CRAVINGS</span><div className="hero-photo-frame"><MenuPhoto x={768} y={26} width={363} height={327} label="Crispy chicken burger from the 4bros menu" /><div className="photo-caption"><span>REAL TASTE.<br />NO SMALL BITES.</span><ArrowUpRight size={34} /></div></div><div className="taste-stamp"><Star size={18} fill="currentColor" /><span>REAL TASTE</span><strong>4BROS</strong><span>REAL BROTHERS</span></div><span className="hero-photo-note">BIG ON FLAVOR. ALWAYS.</span></div>
    </div></section>
    <div className="flavor-strip" aria-hidden="true"><div>BURGERS <span>✦</span> SHAWARMA <span>✦</span> ROLLS <span>✦</span> SANDWICHES <span>✦</span> REAL BROS <span>✦</span> BIG FLAVOR <span>✦</span></div></div>
    <section className="menu-section" id="menu"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="small-cross">✦</span> THE GOOD STUFF</p><h2>MEET YOUR <span>NEXT CRAVING.</span></h2></div><a href="/images/menu-original.jpeg" target="_blank" rel="noreferrer" className="text-link">View original menu <ArrowUpRight size={17} /></a></div><div className="menu-category-nav" aria-label="Menu categories">{categories.map((c,i)=><a key={c.id} href={`#${c.id}`}><span>0{i+1}</span>{c.name}<ArrowUpRight size={15}/></a>)}</div><div className="menu-grid">{categories.map((category,index)=><MenuCard key={category.id} category={category} index={index}/>)}</div></div></section>
    <section className="sauce-section" id="sauces"><div className="container"><div className="sauce-panel"><div className="sauce-heading"><div><p className="eyebrow">A LITTLE EXTRA. A LOT OF FLAVOR.</p><h2>MAKE IT <span>SAUCY.</span></h2></div><div className="dip-price"><span>DIP SAUCE</span><strong>50 <small>PKR</small></strong></div></div><ul className="sauce-list">{sauces.map((sauce,i)=><li key={sauce}><span>0{i+1}</span>{sauce}</li>)}</ul><MenuPhoto x={36} y={1404} width={1064} height={76} label="Nine dip sauces pictured on the original 4bros menu" /></div><p className="menu-note">All prices are in PKR. Petty Burger is listed at PKR 280–320; ask the team about the available options.</p></div></section>
    <section className="contact-section" id="contact"><div className="container contact-inner"><div><p className="eyebrow">HAFIZABAD, THIS ONE’S FOR YOU.</p><h2>HUNGRY?<br />CALL YOUR <span>BROS.</span></h2><p>Pick your favorites. Message us on WhatsApp or give us a call to place your order.</p><a href={whatsappUrl} target="_blank" rel="noreferrer" className="button button-cream"><MessageCircle size={20}/> Order on WhatsApp <ArrowUpRight size={18}/></a></div><div className="contact-details"><div className="location-label"><MapPin size={21}/><span>FIND YOUR FLAVOR<strong>Hafizabad, Pakistan</strong></span></div>{business.phones.map((p,i)=><a href={`tel:${p.international}`} className="contact-phone" key={p.international}><span className="phone-prefix">0{i+1} / CALL THE BROS</span><span>{p.display}<ArrowUpRight size={26}/></span></a>)}<p className="contact-note">Call us for directions, opening hours, and order availability.</p></div></div></section>
  </main><footer><div className="container footer-top"><a href="#home" className="brand-link"><Logo /><span>4BROS<span className="brand-sub">REAL TASTE. REAL BROTHERS.</span></span></a><p>FAST FOOD. BIG FLAVOR. HAFIZABAD.</p><a href="/images/menu-original.jpeg" download="4bros-menu.jpeg" className="text-link">Save the menu <ArrowDownToLine size={17}/></a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} 4bros. All rights reserved.</span><span>All prices in Pakistani Rupees (PKR).</span><a href="#home">Back to top ↑</a></div></footer><a href={whatsappUrl} target="_blank" rel="noreferrer" className="mobile-order"><MessageCircle size={20}/> Order on WhatsApp <ArrowUpRight size={18}/></a></>;
}
